# Generated by Django 5.0.3 on 2024-05-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
