# Generated by Django 5.0.3 on 2024-05-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_activeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUser',
        ),
    ]
