# Generated by Django 5.0.3 on 2024-03-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(max_length=12)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('gradeLvl', models.CharField(max_length=50, null=True)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('guardian', models.CharField(max_length=50, null=True)),
                ('semester', models.CharField(max_length=50, null=True)),
                ('track', models.CharField(max_length=50, null=True)),
                ('strand', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('contactNo', models.CharField(max_length=50)),
                ('Bday', models.DateField()),
            ],
        ),
    ]
