# Generated by Django 5.0.3 on 2024-05-24 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='father',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='gradeLvl',
        ),
        migrations.RemoveField(
            model_name='account',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='account',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='account',
            name='strand',
        ),
        migrations.RemoveField(
            model_name='account',
            name='track',
        ),
    ]
