# Generated by Django 5.0.3 on 2024-05-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_rename_father_account_email_remove_account_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
