# Generated by Django 5.0.3 on 2024-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_account_email_alter_account_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='contactNo',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='position',
        ),
        migrations.AddField(
            model_name='librarian',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='fname',
            field=models.CharField(default='', max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='librarian',
            name='lname',
            field=models.CharField(default='', max_length=50, verbose_name='Last Name'),
        ),
    ]
