# Generated by Django 5.0.3 on 2024-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookTitle', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Date', models.DateField()),
                ('Category', models.CharField(max_length=100)),
                ('BookFile', models.FileField(default='default_value.pdf', upload_to='books/files/')),
                ('BookImage', models.ImageField(default='default_image.jpg', upload_to='books/images/')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
    ]
