<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-05-25 13:56
=======
# Generated by Django 5.0.3 on 2024-05-25 15:19
>>>>>>> 72c508e04b02b667a9ab3137e1c176f909d97d31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 13, 56, 26, 417148, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 19, 18, 639299, tzinfo=datetime.timezone.utc)),
>>>>>>> 72c508e04b02b667a9ab3137e1c176f909d97d31
        ),
    ]
