# Generated by Django 5.0.3 on 2024-05-24 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='research_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 16, 40, 38, 865937, tzinfo=datetime.timezone.utc)),
        ),
    ]
