<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-05-25 13:59
=======
# Generated by Django 5.0.3 on 2024-05-25 15:19
>>>>>>> 72c508e04b02b667a9ab3137e1c176f909d97d31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 13, 59, 29, 98379, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 19, 21, 463721, tzinfo=datetime.timezone.utc)),
>>>>>>> 72c508e04b02b667a9ab3137e1c176f909d97d31
        ),
    ]
