# Generated by Django 5.0.3 on 2024-05-23 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Def', max_length=100)),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 20, 10, 0, 321796, tzinfo=datetime.timezone.utc)),
        ),
    ]
