# Generated by Django 5.0.3 on 2024-05-25 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='TimesBorrow',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 15, 24, 33, 301078, tzinfo=datetime.timezone.utc)),
        ),
    ]
