# Generated by Django 5.0.3 on 2024-05-23 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_subcategory_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 20, 12, 8, 883926, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
