# Generated by Django 5.0.3 on 2024-05-24 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 17, 53, 40, 900553, tzinfo=datetime.timezone.utc)),
        ),
    ]
