# Generated by Django 5.0.3 on 2024-05-23 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_borrowrequest_expires_at_alter_category_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='SubCategory',
            field=models.ManyToManyField(to='librarian.subcategory'),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 20, 15, 37, 998178, tzinfo=datetime.timezone.utc)),
        ),
    ]
