# Generated by Django 5.0.3 on 2024-05-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 16, 57, 21, 582701, tzinfo=datetime.timezone.utc)),
        ),
    ]
