# Generated by Django 5.0.3 on 2024-05-26 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 12, 46, 16, 989968, tzinfo=datetime.timezone.utc)),
        ),
    ]
