# Generated by Django 5.0.3 on 2024-04-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0009_books_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Categories',
            new_name='Category',
        ),
    ]
