# Generated by Django 5.0.3 on 2024-05-16 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0015_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 15, 38, 21, 184807, tzinfo=datetime.timezone.utc)),
        ),
    ]
