# Generated by Django 5.0.3 on 2024-05-17 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0019_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 12, 36, 30, 619068, tzinfo=datetime.timezone.utc)),
        ),
    ]
