# Generated by Django 5.0.3 on 2024-05-19 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0021_alter_borrowrequest_expires_at_approvedrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 3, 31, 30, 887882, tzinfo=datetime.timezone.utc)),
        ),
    ]
