# Generated by Django 5.0.3 on 2024-05-21 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0022_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 7, 38, 54, 849059, tzinfo=datetime.timezone.utc)),
        ),
    ]
