# Generated by Django 5.0.3 on 2024-05-21 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0023_alter_borrowrequest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 24, 10, 23, 47, 56954, tzinfo=datetime.timezone.utc)),
        ),
    ]
