# Generated by Django 5.0.3 on 2024-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_remove_books_bookmarked_books_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='PageViews',
            field=models.IntegerField(default=0),
        ),
    ]
