# Generated by Django 5.0.3 on 2024-04-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_books_pageviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('selfhelp', 'Self-Help'), ('other', 'Other')], max_length=100),
        ),
    ]
