# Generated by Django 5.0.3 on 2024-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0004_alter_books_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Language',
            field=models.CharField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('other', 'Other')], default='english', max_length=100),
        ),
    ]
