# Generated by Django 5.0.3 on 2024-04-27 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0011_books_borrow_requested_by_books_borrowed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='borrowed_by',
        ),
        migrations.RemoveField(
            model_name='books',
            name='borrow_requested_by',
        ),
        migrations.AddField(
            model_name='books',
            name='borrow_requested_by',
            field=models.ManyToManyField(blank=True, related_name='borrow_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
