# Generated by Django 5.0.3 on 2024-04-27 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0013_remove_books_borrow_requested_by_borrowrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='borrowed',
            field=models.ManyToManyField(blank='True', related_name='borrow', to=settings.AUTH_USER_MODEL),
        ),
    ]
