# Generated by Django 5.0.3 on 2024-05-14 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0014_books_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 17, 10, 56, 3, 914125, tzinfo=datetime.timezone.utc)),
        ),
    ]
